on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hydephp/action@config-array
        with:
          deploy-to: "artifact"
          config: |
            # Enter key-value Yaml here:
            name: Example
            sha: {{ github.sha }}
